#[cfg(test)]
pub fn get_test_data() -> Vec<(String, String)> {
    let data = vec![
        (
            // >ERR209056;k59_14625
            "ATAAACATAAATACATATGCGGGAGAGCTTCCGCTGACTCCCACGACCACATCCATCAGACGCTCCGGTACGACACTTGCGATGCCGAAGGAACGGAGCAGGGAAAGCACCTGCTCTGTCTCATCCTCCGTGACATTTTCTCCGATGCATACACCGGTACAGCCCTCCAGTACCAGGGCCGGCGTATTGGGCATGCAGCGGATCAGCTTAAGCTCCGGTCTGTCAAATGCATCCTTC".to_string(),
            // >ERR209055;k59_2911
            "TTCACCGGGATGTTTTCCGGTCTCCAGCACCATTTTGGCACTGCCGAGTACGGACTGTGCTGCGAATTCATAGGCCTGTTTTCTGGGCATTCCGGCTGCCACAGCTTCATCCGCCATGGCCTCAATAAACATAAATACATATGCGGGAGAGCTTCCGCTGACTCCCACGACCACATCCATCAGACGCTCCGGTACGACACTTGCGATGCCGAAGGAACGGAGCAGGGAAAGCACCTGCTCTGTCTCATCCTCCGTGACATTTTC".to_string()
        ),
        (
            "ATAAACATAAATACATATGCGGGAGAGCTTCCGCTGACTCCCACGACCACATCCATCAGACGCTCCGGTACGACACTTGCGATGCCGAAGGAACGGAGCAGGGAAAGCACCTGCTCTGTCTCATCCTCCGTGACATTTTCTCCGATGCATACACCGGTACAGCCCTCCAGTACCAGGGCCGGCGTATTGGGCATGCAGCGGATCAGCTTAAGCTCCGGTCTGTCAAATGCATCCTTC".to_string(),
            "CCGCTGACTCCCACGACCACATCCATCAGACGCTCCGGTACGACACTTGCGATGCCGAAGGACGGAGCAGGGAAAGCACCTGCTCTGTCTCATCCTCCGTGACATTTTCTCCGATGCATACACCGGTACAGCCCTCCAGTACCAGGGCCGGCGTATTGGGCATGCAGCGGATCAGCTTAAGCTCCGGTCTGTCAAATTCATCCTTCGACAAACCTGTGGCCAAAACTCTTGAAGTCAGTAAATATCCTGCCATTTCTTGCTGCTTCTCATATCGCGACTGAATATCAATGCCAGATGACAGGGCAGTAATTGATTGAAGT".to_string(),
        )
    ];
    data
}